<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8"/>
        <title>Группа не найдена</title>
        <link rel="stylesheet" type="text/css" href="<?php echo URL?>public/css/grouppage/404.css">
    </head>
<body>
<div class="container">
    <img src="<?php echo URL;?>public/img/loop.png">
    <h1>404</h1>
    <h3>Страница группы не найдена</h3>
    <h4>Страница группы с идентификатором "<?php echo $data['id'];?>" не найдена. Обратитесь к своему преподавателю или проверте введенную информацию.</h4>
    <span>Перейти к <a href="<?php echo URL;?>app/groups">списку групп</a></span>
</div>
</body>
</html>