<link rel="stylesheet" href="<?php print URL; ?>public/css/common/common.css" />
<link rel="stylesheet" href="<?php print URL; ?>public/css/admin/admin.css"/>
<link rel="stylesheet" href="<?php print URL; ?>public/css/user.css"/>
<link rel="stylesheet" href="<?php print URL; ?>public/css/common/footer/footer.css">
<footer class="footer">
    <div style="position: relative">
        <div class="background"></div>
        <div class="clear-both"></div>
    </div>
</footer>