
<!--<link rel='stylesheet' href="--><?php //print URL; ?><!--public/js/vendor/jquery-custom-scrollbar-0.5.5/jquery.custom-scrollbar.css"" />-->
<link rel='stylesheet' href="<?php print URL; ?>public/css/common/common.css" />
<link rel='stylesheet' href="<?php print URL; ?>public/css/user.css" />
<link rel='stylesheet' href="<?php print URL; ?>public/css/common/header/header.css" />

<?php
if (isset($data['files'])) {
    foreach ($data['files'] as $file) {
        echo "<link rel = \"stylesheet\" href = URL.'public/css/'.$file>";
    }
}
?>

<script src="<?php print URL; ?>public/js/vendor/knockout-3.2.0.js"></script>
<script src="<?php print URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js"></script>
<script src="<?php print URL; ?>public/js/vendor/jquery.slimscroll.js"></script>
<!--<script src="--><?php //print URL; ?><!--public/js/vendor/jquery-custom-scrollbar-0.5.5/jquery.custom-scrollbar.js"></script>-->
<script src="<?php print URL; ?>public/js/app/common.js"></script>
<script src="<?php print URL; ?>public/js/app/common/header/header.js"></script>

<header class="header">
    <div class="background"></div>
    <section class="menu">
        <?php
        $URIs = ['app/calendar','app/groups'];
        $names = ['Расписание','Группы'];
        $currentPage = isset($data['currentPage'])?$data['currentPage']:'';
        for($i=0;$i<count($URIs);$i++){
            $uri=explode("/",$URIs[$i]);
            $page =$uri[count($uri)-1];
            $link = "<a class='button' href=".URL.$URIs[$i].">".$names[$i]."</a>";
            if($page==$currentPage){
                $link = "<a class='button underline' href=".URL.$URIs[$i].">".$names[$i]."</a>";
            }
            echo $link;
        }

        ?>
    </section>

    <section class="login" id="login">
        <article class="user" id="activeUser">
            <div class="table-cell">
                <img class="avatar" id="activeUserPhoto" src="<?php echo  $data['photo']  ?>" />
            </div>
            <section class="info">
                <h2 class="name" id="activeUserName">
                    <?php echo htmlspecialchars($data['name'])  ?>
                    <img class="arrow-down" src="<?php echo URL; ?>public/img/arrow-down.png"/>
                </h2>
                <h3 class="role" id="activeUserRole">
                    <?php echo htmlspecialchars($data['status'])  ?>
                </h3>
            </section>
            <a style="display: none" class="logout" id="logout" href="<?php echo $_SESSION['logout_link'];?>">
                <img style="width:20px; display: block;" src="<?php echo URL; ?>public/img/exit.svg"/>
            </a>
            <div class="fill-gape"></div>
            <section class="expand">
                <ul class="controls">
                    <li>
                        <a>
                            <div class="icon-wrapper">
                                <img class="icon" src="<?php echo URL; ?>public/img/settings.svg"/>
                            </div>
                            <div class="h-label">
                                Настройки
                            </div>
                        </a>
                    </li>
                    <li>
                        <a>
                            <div class="icon-wrapper">
                                <img class="icon" src="<?php echo URL; ?>public/img/user.svg"/>
                            </div>
                            <div class="h-label">
                                Профиль
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $_SESSION['logout_link'];?>">
                            <div class="icon-wrapper">
                                <img class="icon" src="<?php echo URL; ?>public/img/power.svg"/>
                            </div>
                            <div class="h-label">
                                Выйти
                            </div>
                        </a>
                    </li>
                </ul>
            </section>
        </article>
    </section>
    <section class="message">
        <div class="message-icon" id="message-icon"></div>
        <div class="message-count">0</div>
    </section>
    <div  class="wrap display-none" id="wrap">
        <div class="content-wrap" id="content-wrap"></div>
    </div>

    <div class="clear-both"></div>
</header>