<link rel='stylesheet' href="<?php print URL; ?>public/css/common/common.css" />
<link rel='stylesheet' href="<?php print URL; ?>public/css/user.css" />
<link rel='stylesheet' href="<?php print URL; ?>public/css/common/header/header.css" />

<?php
if (isset($data['files'])) {
    foreach ($data['files'] as $file) {
        echo "<link rel = \"stylesheet\" href = URL.'public/css/'.$file>";
    }
}
?>


<script src="<?php print URL; ?>public/js/vendor/knockout-3.2.0.js"></script>
<script src="<?php print URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js"></script>
<script src="<?php print URL; ?>public/js/app/common.js"></script>
<script src="<?php print URL; ?>public/js/app/common/header/header.js"></script>


<header class="header">
    <div class="background"></div>
    <img class="logo" src="<?php echo URL; ?>public/img/logo.png"/>
    <section class="login" id="login">
        <article class="user" id="activeUser">
            <section class="info">
                <h2 class="name" id="activeUserName">
                    <?php echo $data['name']  ?>
                </h2>
                <h3 class="role" id="activeUserRole">
                    <?php echo $data['status']  ?>
                </h3>
                <a class="logout" id="logout" href="<?php echo $_SESSION['logout_link'];?>">Выйти из системы</a>
            </section>
            <img class="avatar" id="activeUserPhoto" src="<?php echo $data['photo']  ?>" />
        </article>
    </section>
    <div class="clear-both"></div>
</header>