<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Расписание</title>
    <link rel="stylesheet" href="<?php print URL; ?>public/css/startPage/bootstrap.css"/>
    <link rel="stylesheet" href="<?php print URL; ?>public/css/startPage/start-page.css" />
    <link rel="stylesheet" href="<?php print URL; ?>public/css/startPage/login_css.css" />
</head>
<body>

<section class="logIn" id="signIn">
    <h1>Расписание</h1>
    <div class="signin" id="signIn">
        <h2>Выберите способ входа</h2>
        <div class="panel panel-default">
            <div class="panel-body">
                <script>
                    window.fbAsyncInit = function() {
                        FB.init({
                            appId      : '384838578363750',
                            xfbml      : true,
                            version    : 'v2.2'
                        });
                    };

                    (function(d, s, id){
                        var js, fjs = d.getElementsByTagName(s)[0];
                        if (d.getElementById(id)) {return;}
                        js = d.createElement(s); js.id = id;
                        js.src = "//connect.facebook.net/en_US/sdk.js";
                        fjs.parentNode.insertBefore(js, fjs);
                    }(document, 'script', 'facebook-jssdk'));
                </script>
                <div
                    class="fb-like"
                    data-share="true"
                    data-width="450"
                    data-show-faces="true">
                </div>
                <div class="button google" href="<?php print URL; ?>app/loging/login">
                    Google
                </div>
                <div class="button facebook" href="<?php print URL; ?>app/loginf/login">
                    Facebook
                </div>
                <!--<a href="#" id='fbLogout' class="btn btn-info">
                      <div class="text">Logout</div>
                  </a >
  <!--                <a href="#" id='check' class="btn btn-info">-->
                <!--                    <div class="text">Check</div>-->
                <!--                </a >-->
            </div>
        </div>
        <!--
        <h2>или зарегистрируйтесь</h2>
        <div class="panel panel-default">
            <div class="panel-body">
                <a href="#" class="btn btn-info">
                    <div class="text">Регистрация для студентов</div>
                </a>
                <a href="#" class="btn btn-info">
                    <div class="text">Регистрация для преподавателей</div>
                </a>
            </div>
        </div>
        -->
    </div>
    <!--
    <div class="not-in-system" id="notInSystem" style="display: none" >
        <h2>Вас нет в системе<br/>зарегистрируйтесь</h2>
        <div class="panel panel-default">
            <div class="panel-body">
                <a href="#" class="btn btn-info">
                    <div class="text">Регистрация для студентов</div>
                </a>
                <a href="#" class="btn btn-info">
                    <div class="text">Регистрация для преподавателей</div>
                </a>
            </div>
        </div>
    </div>
    -->
</section>



<!--<script src="https://apis.google.com/js/client:platform.js"></script>-->
<script src="<?php print URL; ?>public/js/vendor/knockout-3.2.0.js"></script>
<script src="<?php print URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js"></script>
<script src="<?php print URL; ?>public/js/app/common.js"></script>
<script src="<?php print URL; ?>public/js/app/signin/login1.js"></script>

</body>
</html>
