
<section class="container">
    <div class="col-lg-12 info-title">
        <a href="<?php echo URL;?>app/groups" class="backButton">Вернуться к списку групп</a>
        <?php if ($data['role'] == 'student'): ?>
            <button class="btn edt dismissButton"
               data-bind="click:function(){deleteUser(<?php echo $data['id'] ?>)}">Покинуть группу</button>
        <?php endif; ?>
        <!--ko ifnot: editGroupName-->
        <div class="col-lg-12 info-title">
            <?php if ($data['role'] == 'teacher'): ?>
                <div>
            <?php endif; ?>
                    <div data-bind="if:havePicture" class="pict-cont">
                        <div class="wrapp">
                            <img data-bind='attr:{src: imgSrc}'>
                        </div>
                    </div>
            <h1 data-bind="text:groupName<?php if($data['role'] == 'teacher'): ?>,click: editTitleOpen<?php endif;?>"></h1>
            <?php if ($data['role'] == 'teacher'): ?>
        </div>
    <?php endif; ?>
        </div>
        <!--/ko-->
        <?php if ($data['role'] == 'teacher'): ?>
            <!--ko if: editGroupName-->
            <div class="col-lg-12 info-title">
                <input id="titleInput" type="text" data-bind="value:groupName, event: {blur: saveTitle}" class="form-control ">
                <span data-bind="text:errorTitleMessage"></span>
            </div>
            <!--/ko-->
        <?php endif; ?>
    </div>

    <div class="col-lg-12 ">

        <?php if ($data['role'] == 'teacher'): ?>
    <div class="col-lg-12">
        <span>По следующей ссылке студенты могут добавляться в группу:</span>
        <div class="col-lg-10">
            <label type="text" data-bind="text:getCode" class="form-control " id="inputName" ></label>
        </div>
        <div class="col-lg-2">
            <a href="#" data-bind="click: changeCode" class="btn code dismissButton">Сгенерировать код</a>
        </div>
        <?php endif; ?>

    </div>

    <section class="groupList col-md-12">


        <div data-bind="foreach: students">
            <!--ko if: fb_account-->
            <!--ko if: notDeleted-->
            <div class=" col-md-6 list-group">
                <div class="list-group-item">
                    <?php if ($data['role'] == 'teacher'): ?>
                        <a href="#" class=" removeStudent"
                           data-bind="click:function(){$parent.dismissStudent(id)}">
                            <img height="20" width="20" src="<?php echo URL; ?>public/img/closeButton.png""></a>
                    <?php endif; ?>

                    <a data-title="Перейти к профилю в Facebook" class="list-group-item-text " target="_blank" data-bind="attr:{href: fb_account}">
                        <img class="avatar" data-bind="attr:{src: fb_photo}" height="70" width="70"></a>
                    <a data-title="Перейти к профилю в Facebook" data-bind="attr:{href: fb_account}" target="_blank"><h4 class="list-group-item-heading"
                                                                               data-bind="text:name"></h4></a>

                </div>
            </div>
            <!--/ko-->

                         <!--ko ifnot: notDeleted-->
            <div class=" col-md-6 list-group">
                <div class="list-group-item deletedStudent">
                    Вы удалили пользователя.  <a href="#" data-bind="click:function(){$parent.restoreUser(id)}">Восстановить</a>
                </div>
            </div>
                         <!--/ko-->
            <!--/ko-->


            <!--ko if: gm_account-->
            <!--ko if: notDeleted-->
            <div class=" col-md-6 list-group" data-bind="if: gm_account">
                <div class="list-group-item">
                    <?php if ($data['role'] == 'teacher'): ?>
                        <a href="#" class=" removeStudent"
                           data-bind="click:function(){$parent.dismissStudent(id)}">
                            <img height="20" width="20" src="<?php echo URL; ?>public/img/closeButton.png""></a>
                    <?php endif; ?>
                    <a data-title="Перейти к профилю в Google+" class="list-group-item-text " target="_blank" data-bind='attr:{href: gm_account}'><img
                            src="https://lh5.googleusercontent.com/-qWNMqcca81Y/AAAAAAAAAAI/AAAAAAAAAAA/g6oiN_9k82A/s120-c/photo.jpg"
                            class="avatar" height="70" width="70"></a>
                    <a data-title="Перейти к профилю в Google+" data-bind="attr:{href: gm_account}" target="_blank"><h4 class="list-group-item-heading"
                                                                               data-bind="text:name" ></h4></a>

                </div>
            </div>
            <!--/ko-->
            <!--ko ifnot: notDeleted-->
            <div class=" col-md-6 list-group">
                <div class="list-group-item deletedStudent">
                    Вы удалили пользователя.  <a href="#" data-bind="click:function(){$parent.restoreUser(id)}">Восстановить</a>
                </div>
            </div>
            <!--/ko-->
            <!--/ko-->
        </div>

    </section>


    <div class="col-lg-12">
        <?php if ($data['role'] == 'teacher'): ?>

        <?php endif; ?>
    </div>


</section>
<script src="<?php echo URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js"></script>
<script src="<?php echo URL; ?>public/js/app/common.js"></script>
<script src="<?php echo URL; ?>public/js/app/grouppage/grouppage.js"></script>

<script src="<?php echo URL; ?>public/js/vendor/knockout-3.2.0.js"></script>
<script src="<?php echo URL; ?>public/js/app/grouppage/API.js"></script>
<script src="<?php echo URL; ?>public/js/app/grouppage/viewModel.js"></script>

<link rel="stylesheet" type="text/css" href="<?php echo URL; ?>public/css/common/bootstrap.css">
<link rel="stylesheet" type="text/css" href="<?php echo URL; ?>public/css/grouppage/grouppage.css">
</body>
</html>