<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Group Page</title>
    <link rel="stylesheet" type="text/css" href="<?php echo URL; ?>public/css/common/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="<?php echo URL; ?>public/css/grouppage/grouppage.css">
</head>
<body>
<section class="container">
    <div class="col-lg-12 info-title">

        <!--ko ifnot: editGroupName-->
            <div class="col-lg-7 info-title">
                <h1 data-bind="text:groupName"></h1>
            </div>
        <?php if ( $data['role'] == 'teacher'): ?>
            <div class = "col-lg-3 info-title">
                <a href="#" data-bind="click: editTitleOpen" class="btn btn-default">Изменить название</a>
            </div>
        <?php endif;?>
        <!--/ko-->
            <?php if ( $data['role'] == 'teacher'): ?>
        <!--ko if: editGroupName-->
            <div class="col-lg-7 info-title">
                <input type="text"  data-bind="value:groupName" class="form-control " >
                <span data-bind="text:errorTitleMessage"></span>
            </div>
        <div class = "col-lg-3 info-title">
            <a href="#" data-bind="click: saveTitle" class="btn btn-default">Сохранить изменения</a>
        </div>

        <!--/ko-->
        <?php endif;?>
    </div>

    <div class="col-lg-12 info-desc ">

        <!--ko ifnot: editDescription-->
            <div class="col-lg-7 info-desc">
                <h3  data-bind="text:description"></h3>
            </div>
        <?php if ( $data['role'] == 'teacher'): ?>
        <div class = "col-lg-3 info-desc">
            <a href="#" data-bind="click: editDescOpen" class="btn btn-default">Изменить описание</a>
        </div>
        <?php endif;?>
        <!--/ko-->
        <?php if ( $data['role'] == 'teacher'): ?>
        <!--ko if: editDescription-->
            <div class="col-lg-7 info-desc">
                <textarea rows= "3" data-bind="value: description" id="inputDesc" class="form-control" ></textarea>
                <span data-bind="text:errorDescMessage"></span>
            </div>
        <div class = "col-lg-3 info-desc">
            <a href="#" data-bind="click: saveDesc" class="btn btn-default">Сохранить описание</a>
        </div>

        <!--/ko-->
        <?php endif;?>
        </div>

    <section class="groupList col-md-12">


        <div data-bind="foreach: students">
            <!--ko if: fb_account-->
            <div class=" col-md-6 list-group" >
                <div  class="list-group-item" >
                    <a class="list-group-item-text " target="_blank" data-bind="attr:{href: fb_account}"><img class="avatar" data-bind="attr:{src: fb_photo}" height="70" width="70"></a>
                    <a data-bind="attr:{href: fb_account}" target="_blank"> <h4 class="list-group-item-heading" data-bind="text:name"></h4></a>

                </div>
            </div>
            <!--/ko-->
            <!--ko if: gm_account-->
            <div class=" col-md-6 list-group" data-bind="if: gm_account">
                <div  class="list-group-item" >
                    <a class="list-group-item-text " target="_blank" data-bind=><img src="https://lh5.googleusercontent.com/-qWNMqcca81Y/AAAAAAAAAAI/AAAAAAAAAAA/g6oiN_9k82A/s120-c/photo.jpg" class="avatar"  height="70" width="70"></a>
                    <a data-bind="attr:{href: gm_account}" target="_blank"><h4 class="list-group-item-heading" data-bind="text:name"></h4></a>

                </div>
            </div>
            <!--/ko-->
        </div>

    </section>


    <div class="col-lg-12">
        <?php if ( $data['role'] == 'teacher'): ?>
            <span>По следующей ссылке студенты могут добавляться в группу:</span>
        <div class="col-lg-8">
            <input type="text"  data-bind="value:getCode" class="form-control " id="inputName" disabled="disabled" >
            </div>  <div class="col-lg-4">
            <a href="#" data-bind="click: changeCode" class="btn btn-default">Сгенерировать код</a>
            </div>
        <?php endif; ?>
        <?php if ($data['role'] == 'student'): ?>
            <a href="#" class="btn btn-default dismissButton">Покинуть группу</a>
        <?php endif; ?>

    </div>


</section>
<script src="<?php echo URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js"></script>
<script src="<?php echo URL; ?>public/js/app/common.js"></script>
<script src="<?php echo URL; ?>public/js/app/grouppage/grouppage.js"></script>

<script src="<?php echo URL; ?>public/js/vendor/knockout-3.2.0.js"></script>
<script src="<?php echo URL; ?>public/js/app/grouppage/api.js"></script>
<script src="<?php echo URL; ?>public/js/app/grouppage/viewModel.js"></script>


</body>
</html>