<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Group Page</title>
    <link rel="stylesheet" type="text/css" href="<?php echo URL; ?>public/css/common/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="<?php echo URL; ?>public/css/grouppage/grouppage.css">
</head>
<body>
<section class="container">
    <!--ko ifnot: editGroupName-->
    <h1 data-bind="text:groupName"></h1>
    <!--/ko-->
    <!--ko if: editGroupName-->
    <input type="text"  data-bind="value:groupName" class="form-control "  disabled="disabled" >
    <!--/ko-->
    <!--ko ifnot: editDescription-->
    <h3  data-bind="text:description"></h3>
    <!--/ko-->
    <!--ko if: editDescription-->
    <textarea data-bind="value:description" id="inputDesc" class="form-control" ></textarea>
    <!--/ko-->
    <section class="groupList col-md-12">


        <div data-bind="foreach: students">
            <div class=" col-md-6 list-group">
                <div  class="list-group-item">
                    <a class="list-group-item-text " target="_blank" data-bind="attr:{href: fb_account}"><img class="avatar" data-bind="attr:{src: fb_photo}" height="70" width="70"></a>
                    <h4 class="list-group-item-heading" data-bind="text:name"></h4>

                </div>
            </div>
        </div>

    </section>


    <div class="col-lg-12">
        <?php if ( $data['role'] == 'teacher'): ?>
            <span>По следующей ссылке студенты могут добавляться в группу:</span>
        <div class="col-lg-8">
            <input type="text"  data-bind="value:getCode" class="form-control " id="inputName" disabled="disabled" >
            </div>  <div class="col-lg-4">
            <a href="#" data-bind="click: changeCode" class="btn btn-default">Сгенерировать код</a>
            </div>
        <?php endif; ?>
        <?php if ($data['role'] == 'student'): ?>
            <a href="#" class="btn btn-default dismissButton">Покинуть группу</a>
        <?php endif; ?>

    </div>


</section>
<script src="<?php echo URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js"></script>
<script src="<?php echo URL; ?>public/js/app/common.js"></script>
<script src="<?php echo URL; ?>public/js/app/grouppage/grouppage.js"></script>

<script src="<?php echo URL; ?>public/js/vendor/knockout-3.2.0.js"></script>
<script src="<?php echo URL; ?>public/js/app/grouppage/api.js"></script>
<script src="<?php echo URL; ?>public/js/app/grouppage/viewModel.js"></script>


</body>
</html>