<link rel='stylesheet' href="<?php print URL; ?>public/css/common/common.css" />
<link rel='stylesheet' href="<?php print URL; ?>public/css/common/header/header.css" />

<script src="<?php print URL; ?>public/js/vendor/knockout-3.2.0.js"></script>
<script src="<?php print URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js"></script>
<script src="<?php print URL; ?>public/js/app/common.js"></script>
<script src="<?php print URL; ?>public/js/app/common/header/header.js"></script>

<header class="header">
    <div class="background"></div>
    <section class="menu">
        <a class="button" href="<?php echo URL; ?>app/admin">Админка</a>
        <a class="button" href="<?php echo $data['database'] ?>">SQLite manager</a>
    </section>
    <div class="clear-both"></div>
</header>