<?php
    echo '<style>';
        require_once (FILE."public/css/common/bootstrap.css");
        require_once (FILE."public/css/common/common.css");
        require_once (FILE."public/css/user.css");
        require_once (FILE."public/css/admin/admin.css");
    echo '</style>';

?>
<img src="https://www.googleapis.com/plus/v1/people/105611229835693385297?fields=image&key=AIzaSyAY5scKxZyMPC8j0PnoX3tCEKtVE_GzT3A"/>
<ul class="user-list" data-bind="foreach: users">

    <li class="user">
        <div class="padding">
            <img class="avatar" data-bind="attr{src: photo}"/>
            <section class="info">
                <h2 class="name" data-bind="text: name"></h2>
                <h3 class="role" data-bind="text: role"></h3>
            </section>
            <!-- ko ifnot: confirmed -->
            <div class="confirm-status" data-bind="click: $parent.confirm">Подтвердить статус</div>
            <!-- /ko -->
            <!-- ko if: confirmed -->
            <div class="confirm-status" data-bind="click: $parent.unConfirm">Статус потвержден. Отменить...</div>
            <!-- /ko -->
            <div class="clear-both"></div>
        </div>
    </li>
</ul>

<?php
    echo '<script>';
        require_once (FILE."public/js/vendor/jQuery/jquery-2.1.1.js");
        require_once (FILE."public/js/app/common.js");
        require_once (FILE."public/js/app/admin/admin.js");
    echo '</script>';
?>
<script>
    load();
</script>
