<link rel="stylesheet" href="<?php echo URL; ?>public/css/common/common.css" />
<link rel="stylesheet" href="<?php echo URL; ?>public/css/common/header/header.css" />
<link rel="stylesheet" href="<?php echo URL; ?>public/css/admin/header.css"/>
<link rel="stylesheet" href="<?php echo URL?>public/css/common/bootstrap.css"/>


<header class="header">
    <div class="background"></div>
    <section class="menu">
        <a class="button" href="<?php echo URL; ?>app/admin">Админка</a>
        <a class="button" href="<?php echo $data['database'] ?>">SQLite manager</a>
        <a id ="mail" class="button"><?php echo $data['email']?></a>
        <button class="btn btn-default add-btn" id="change">Изменить</button>
        <label><input class="form-control" type="text" id="mailInput"/></label>
        <button class="btn btn-default add-btn" id="submit">Сохранить</button>
    </section>
    <div class="clear-both"></div>
</header>
<script src="<?php echo URL; ?>public/js/vendor/knockout-3.2.0.js"></script>
<script src="<?php echo URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js"></script>
<script src="<?php echo URL; ?>public/js/app/common.js"></script>
<script src="<?php echo URL; ?>public/js/app/common/header/header.js"></script>
<script src="<?php echo URL;?>public/js/app/admin/header.js"></script>