<?php
echo '<style>';
require_once (DOC_ROOT."public/css/common/bootstrap.css");
require_once (DOC_ROOT."public/css/common/common.css");
require_once (DOC_ROOT."public/css/user.css");
require_once (DOC_ROOT."public/css/admin/admin.css");
require_once (DOC_ROOT."public/css/groups/groups.css");
require_once (DOC_ROOT."public/css/groups/create_group.css");
echo '</style>';
?>

<section class="container">
    <div id="formCreate">
        <form id="create1" class="bs-docs-example form-horizontal">
            <div class="form-group">
                <label for="inputName" class="bold">Название групы</label>
                <input name="name" type="text" class="form-control" id="inputName" >
                <div id="error1" class="info-error">Введите название групы</div>
                <div id="error3" class="info-error">Название должно содержать только буквы, цифры и знаки пунктуации</div>
            </div>
            <div class="form-group">
                <label for="inputDesc" class="bold">Описание</label>
                <textarea name="descr" id="inputDesc" class="form-control"></textarea>
                <div id="error2" class="info-error">Введите описание групы</div>
                <div id="error4" class="info-error">Описание должно содержать только буквы, цифры и знаки пунктуации</div>
            </div>
            <div class="form-group">
                <input name="photo" type="file" id="photo" class="photo-button"/>
                <div id="error5">Выберите изображение формата png, jpg или gif</div>
            </div>
            <button id="createButton" type="button" class="btn btn-default">Создать группу</button>
        </form>
    </div>
    <div id="afterCreate">
        <div class="table">
            <div class="tr">
                <div class="td h200">
                    Cсылка на группу <b><a href="#" id="linkNewOnGroup"></a></b><br />
                    Инвайт: <b><span id="groupInvite"></span></b>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="<?php echo URL; ?>public/js/app/groups/create.js"></script>