<div class="container">
    <div id="formCreate">
        <form id="create1" class="bs-docs-example form-horizontal">
            <div class="form-group">
                <label for="inputName" class="bold">Ім'я групи</label>
                <input name="name" type="text" class="form-control" id="inputName" placeholder="Введіть ім'я групи">
            </div>
            <div class="form-group">
                <label for="inputDesc" class="bold">Опис</label>
                <textarea name="descr" id="inputDesc" class="form-control" placeholder="Введіть опис групи"></textarea>
            </div>
            <input name="photo" type="file" />
            <button id="createButton" type="button" class="btn btn-default">Создать групу</button>
        </form>
    </div>
    <div id="afterCreate">
        <div class="table">
            <div class="tr">
                <div class="td h200">
                    Посилання на групу <a href="#" id="linkNewOnGroup"></a><br />
                    Інвайт: <span id="groupInvite"></span>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo URL; ?>public/js/app/groups/create.js"></script>