<?php
echo '<style>';
require_once (DOC_ROOT."public/css/common/bootstrap.css");
require_once (DOC_ROOT."public/css/common/common.css");
require_once (DOC_ROOT."public/css/user.css");
require_once (DOC_ROOT."public/css/admin/admin.css");
require_once (DOC_ROOT."public/css/groups/groups.css");
require_once (DOC_ROOT."public/css/groups/create_group.css");
echo '</style>';
?>

<section class="container">
    <div id="formCreate">
        <form id="create1" class="bs-docs-example form-horizontal">
            <div class="form-group">
                <label for="inputName" class="bold">Название групы</label>
                <input name="name" type="text" class="form-control" id="inputName" >
                <div id="error7" class="info-error">Имя группы должно быть уникальным</div>
                <div id="error1" class="info-error">Введите название групы</div>
                <div id="error3" class="info-error">Название должно содержать только буквы, цифры и знаки пунктуации</div>
            </div>
            <!--
            <div class="form-group">
                <label for="inputDesc" class="bold">Описание</label>
                <textarea name="descr" id="inputDesc" class="form-control"></textarea>
                <div id="error2" class="info-error">Введите описание групы</div>
                <div id="error4" class="info-error">Описание должно содержать только буквы, цифры и знаки пунктуации</div>
            </div>
            -->
            <div class="form-group">
                <div class="file_button_container" id="file_button_container">
                    <span>Выберите файл</span>
                    <input name="photo" id="photo" type="file" />
                </div>
                <div id="file_name">
                    Ничего не выбрано
                </div>
                <div id="error5">Выберите изображение формата png, jpg, gif и не больше 4 мб</div>
                <div id="error_file"></div>
            </div>
            <button id="createButton" type="button" class="btn btn-default">Создать группу</button>
            <div id="after_error" style='display: block; margin-left: -15px; padding: 3px;' class="info-error"></div>
        </form>
    </div>
</section>
<script src="<?php echo URL; ?>public/js/app/groups/create.js"></script>