
<link rel="stylesheet" type="text/css" href="<?php print URL; ?>public/css/common/bootstrap.css">
<link rel="stylesheet" type="text/css" href="<?php print URL; ?>public/css/groups/groups.css">

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Групи</h3>
                    <div class="pull-right">
							<span class="clickable filter" data-toggle="tooltip" title="Toggle table filter" data-container="body">
								<i class="glyphicon glyphicon-filter"></i>
							</span>
                    </div>
                </div>
                <div class="panel-body">
                    <input type="text" class="form-control" id="task-table-filter" data-action="filter" data-filters="#task-table" placeholder="Пошук по групам" />
                </div>
                <table class="table table-hover" id="task-table">
                    <thead>

                    <tr>
                        <th>#</th>
                        <th>Група</th>
                        <th>Вчитель</th>
                        <th>Наступне заняття</th>
                    </tr>
                    </thead>
                    <tbody>
                    <!-- list -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="<?php print URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js"></script>
<script src="<?php print URL; ?>public/js/app/common.js"></script>
<script src="<?php print URL; ?>public/js/app/groups/groups.js"></script>