<?php
echo '<style>';
require_once (DOC_ROOT."public/css/common/bootstrap.css");
require_once (DOC_ROOT."public/css/common/common.css");
require_once (DOC_ROOT."public/css/user.css");
require_once (DOC_ROOT."public/css/admin/admin.css");
require_once (DOC_ROOT."public/css/groups/groups.css");
echo '</style>';
?>

    <section class="container">
        <?php if ($data['status'] == 'teacher'): ?>
            <a class="btn btn-default" style="margin: 10px; padding: 3px" href="<?php echo URL; ?>app/groups/create">создать группу</a>
        <?php endif; ?>
        <div class="group-list">
            <?php foreach ($data['groups'] as $group) : ?>
            <div class="group">
                <?php if ($group['photo'] == null): ?>
                    <div class="group-icon" style="background-image: url(<?php echo URL . 'public/users_files/images/default/default_group_photo.jpg'; ?>)"></div>
                <?php else: ?>
                    <div class="group-icon" style="background-image: url(<?php echo URL . 'public/users_files/images/groups_photo/' . $group['photo']; ?>)"></div>
                <?php endif; ?>
                    <div class="padding-10px">
                    <h3 class="group-name"><a href="<?php echo URL . 'app/grouppage/id' . $group['group_id']; ?>"><?php echo $group['name']; ?></a></h3>
                    <p class="group-description"><?php echo $group['descr']; ?></p>
                    <div class="next-lesson">
                        <div>
                            Преподаватель:
                        </div>
                        <div class="time"><?php echo $group['teacher_fn'] . ' ' . $group['teacher_ln']; ?></div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </section>
<script src="<?php echo URL; ?>public/js/app/common.js"></script>
<script src="<?php echo URL; ?>public/js/app/groups/groups.js"></script>