<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Администрирование</title>
    <link rel="stylesheet" href='../../../src/public/css/common/common.css' />
    <link rel="stylesheet" href='../../../src/public/css/admin/admin.css'/>
    <link rel="stylesheet" href='../../../src/public/css/user.css'/>
    <link rel="stylesheet" href='../../../src/public/css/common/header.css'>

</head>
<body>

<ul class="user-list" data-bind="foreach: users">
    <li class="user">
        <div class="padding">
            <img class="avatar" data-bind="attr{src: photo}"/>
            <section class="info">
                <h2 class="name" data-bind="text: name"></h2>
                <h3 class="role" data-bind="text: role"></h3>
            </section>
            <!-- ko ifnot: confirmed -->
            <div class="confirm-status" data-bind="click: $parent.confirm">Подтвердить статус</div>
            <!-- /ko -->
            <!-- ko if: confirmed -->
            <div class="confirm-status" data-bind="click: $parent.unConfirm">Статус потвержден. Отменить...</div>
            <!-- /ko -->
            <div class="clear-both"></div>
        </div>
    </li>
</ul>
<script src='../../../src/public/js/vendor/knockout-3.2.0.js'></script>
<script src='../../../src/public/js/vendor/jQuery/jquery-2.1.1.js'></script>
<script src='../../../src/public/js/app/common.js'></script>
<script src='../../../src/public/js/app/admin/admin.js'></script>
<script>
    load();
</script>
</body>
</html>