
<link rel="stylesheet" type="text/css" href="<?php echo URL; ?>public/css/common/bootstrap.css">
<link rel="stylesheet" type="text/css" href="<?php echo URL; ?>public/css/common/common.css">
<link rel="stylesheet" type="text/css" href="<?php echo URL; ?>public/css/user.css">
<link rel="stylesheet" type="text/css" href="<?php echo URL; ?>public/css/admin/admin.css">
<link rel="stylesheet" type="text/css" href="<?php echo URL; ?>public/css/groups/groups.css">



<?php if ($data['status'] == 'teacher'): ?>
    <div data-bind="attr:{class:loadScr}" id="loadScreen"><img src="<?php echo URL?>public/img/load.gif"></div>
<section class="container">
    <div class="go-away"><a href="<?php echo URL?>app/groups"><img width="30" height="30" src="<?php echo URL;?>public/img/arrow.png">Назад</a></div>
    <div class="archiveTitle">Вы находитесь в архиве групп. Для восстановления группы кликните по иконке!</div>
    <div data-bind="foreach: groups" class="group-list">
        <div class="group-container">
        <div class="group">
            <div class="icon-container">
                <a><img class="group-icon" data-bind="attr: {src: imgSrc}"/></a>
            </div>
            <div>
                <img data-bind="click:function(){$parent.restore($data.groupId, $element)}" class="dearchive-icon" src="<?php echo URL;?>/public/img/dearchive.png">
            </div>
            <div class="padding-10px">
                <h3 class="group-name" data-bind="text: name()"></h3>

                <div class="next-lesson">
                    <div>
                        Преподаватель:
                    </div>
                    <div class="time" data-bind="text: teacher"></div>
                </div>
           </div>
        </div>
        </div>

    </div>
</section>
<?php endif; ?>
<script src="<?php echo URL; ?>public/js/vendor/somelibrary.js"></script>
<script src="<?php echo URL; ?>public/js/app/common.js"></script>
<script src="<?php echo URL; ?>public/js/vendor/knockout-3.2.0.js"></script>
<script src="<?php echo URL; ?>public/js/app/groups/archive.js"></script>
