
<link rel='stylesheet' href='<?php print URL; ?>public/js/vendor/fullcalendar-2.2.6/fullcalendar.css' />
<link rel='stylesheet' href='<?php print URL; ?>public/js/vendor/jQuery/jquery-ui.min.css'/>
<link rel='stylesheet' href='<?php print URL; ?>public/css/calendar/common.css'/>
<link rel='stylesheet' href='<?php print URL; ?>public/css/common/bootstrap.css'/>
<link rel='stylesheet' href='<?php print URL; ?>public/css/calendar/tooltip.css'/>




<div class="my-tooltip" id="tooltip">
    <h3  id="tooltipTitle">Title</h3>
    <div class="top">
        <div class="author" id="tooltipAuthor">author</div>
        <div class="time-tooltip">
            <span class="tooltip-date" id="tooltipDate"></span>
            <span class="tooltip-time-start-end" id ='tooltipTimeStartEnd'></span>
        </div>
    </div>
<!--    <div class="time">-->
<!--        <span id="tooltipStart">start</span>-<span id="tooltipEnd">end</span>-->
<!--    </div>-->

    <div class="groooooooooooooooooops">Групы:
        <div id="myTooltipGroupList"></div>
    </div>


</div>

<div class="calendar" id='calendar'></div>

<div id="exportPopup">

</div>

<script>
    function loadExportPopup(){
        $.ajax({
            url: url+'app/calendar/exportPopup',
            type: 'GET',
            success: function (response){
                document.getElementById("exportPopup").innerHTML = response;
            }
        });
    }
    loadExportPopup();

    function loginGoogle(){
        window.location.href = url+'app/loging/login';
    }

    function exportLesson(lesson, callback){
        $.ajax({
            url: url + 'app/calendar/exportEvent',
            type: 'POST',
            data: lesson,
            success: function(response){
                console.log ('exported');
                callback();
            },
            error: function(e){
                //;
            }
        });
    }

    function exportAll(calendarId) {
        var lessons = fullEventFor;
        var counter = 0;

        var success =  document.getElementById('successfullyExported');
        success.style.display = 'none';

        var bar = document.getElementById('exportProgress');
        bar.style.display='block';
        bar.setAttribute('max',lessons.length);
        bar.setAttribute('value','0');
        for (var i =0; i< lessons.length;i++) {
            function callback(){
                bar.setAttribute('value',bar.getAttribute('value')*1+1);
                if (bar.getAttribute('value')*1 >= lessons.length){
                    success.style.display = 'block';
                }
            }
            //if (i>0) return;
            var lessonId = lessons[i].id;
            var userId = lessons[i].teacher;
            var lesson = {lessonId: lessonId, userId: userId};
            exportLesson({lesson: lesson,calendarId:calendarId}, callback);
        }
    }

</script>

<script src='<?php print URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js'></script>
<script src='<?php print URL; ?>public/js/vendor/fullcalendar-2.2.6/moment.min.js'></script>
<script src='<?php print URL; ?>public/js/vendor/fullcalendar-2.2.6/fullcalendar.js'></script>


<script src='<?php print URL; ?>public/js/app/common.js'></script>
<script src='<?php print URL; ?>public/js/app/calendar/Calendar.js'></script>
<script src='<?php print URL; ?>public/js/app/calendar/ajax.js'></script>
<script src='<?php print URL; ?>public/js/app/calendar/ajaxParam.js'></script>

<?php if ($data['status'] == 'teacher'): ?>
    <script type='text/javascript' src='<?php print URL; ?>public/js/app/calendar/customselect/customselect.js'></script>
    <script type='text/javascript' src='<?php print URL; ?>public/js/app/calendar/setselect.js'></script>
    <script type='text/javascript' src='<?php print URL; ?>public/js/vendor/jQuery/jquery.mask.js'></script>
    <script src='<?php print URL; ?>public/js/app/calendar/teacher.js'></script>
    <script type='text/javascript' src='<?php print URL; ?>public/js/app/calendar/tcal/tcal.js'></script>
<?php else: ?>

    <script src='<?php print URL; ?>public/js/app/calendar/student.js'></script>
<?php endif; ?>

<!--</body>-->
<!--</html>-->