<link rel='stylesheet' href='<?php print URL; ?>public/js/vendor/fullcalendar-2.2.6/fullcalendar.css' />
<link rel='stylesheet' href='<?php print URL; ?>public/js/vendor/jQuery/jquery-ui.min.css'/>
<link rel='stylesheet' href='<?php print URL; ?>public/css/calendar/common.css'/>
<link rel='stylesheet' href='<?php print URL; ?>public/css/common/bootstrap.css'/>
<link rel='stylesheet' href='<?php print URL; ?>public/css/calendar/tooltip.css'/>

<div class="my-tooltip" id="tooltip">
    <h3  id="tooltipTitle">Title</h3>
    <div class="top">
        <div class="author" id="tooltipAuthor">author</div>
        <div class="time-tooltip">
            <span class="tooltip-date" id="tooltipDate"></span>
            <span class="tooltip-time-start-end" id ='tooltipTimeStartEnd'></span>
        </div>
    </div>
    <div class="groooooooooooooooooops">Групы:
        <div id="myTooltipGroupList"></div>
    </div>
</div>

<link rel='stylesheet' href='<?php print URL; ?>public/css/calendar/export.css'/>
<div class="export-wrapper" >
    <div class="export-button position-absolute" onclick="showExportPopup()">
        Экспорт
        <img class="arrow-down" src="<?php echo URL; ?>public/img/arrow-down.png"/>
    </div>
    <div id="exportPopup">
        <script>
            $('#exportPopup').hide();
        </script>
        <?php if(Session::has('gm_ID')): ?>
            <div class="export-popup">
                <div>Выберите календарь для експорта уроков</div>
                <div class="calendar-list">
                    <select id="selectCalendar">
                        <?php foreach($data['googleCalendars'] as $calendar):?>
                            <option value="<?php echo $calendar['id']?>">
                                <?php echo $calendar['name'];?>
                            </option>
                        <?php endforeach;?>
                    </select>
                    <button onclick="exportAll()">
                        Экспортировать
                    </button>
                </div>
                <progress class='export-progress' id="exportProgress" value="29" max="100">
                </progress>
                <div class="successfully-exported" id="successfullyExported">
                    Занятия успешно експортированы!
                </div>
            </div>
        <?php endif ?>
        <?php if(!Session::has('gm_ID')):?>
            <div class="export-popup">
            <div class="export-title">Для експорта уроков нужно</div>
            <div class="export-button" onclick="loginGoogle()">войти через Google+</div>
            </div>
        <?php endif?>
    </div>
</div>
<div class="clear-both"></div>
<script src='<?php print URL; ?>public/js/app/calendar/export.js'></script>

<div class="calendar" id='calendar'></div>

<script src='<?php print URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js'></script>
<script src='<?php print URL; ?>public/js/vendor/fullcalendar-2.2.6/moment.min.js'></script>
<script src='<?php print URL; ?>public/js/vendor/fullcalendar-2.2.6/fullcalendar.js'></script>


<script src='<?php print URL; ?>public/js/app/common.js'></script>
<script src='<?php print URL; ?>public/js/app/calendar/Calendar.js'></script>
<script src='<?php print URL; ?>public/js/app/calendar/ajax.js'></script>
<script src='<?php print URL; ?>public/js/app/calendar/ajaxParam.js'></script>

<?php if ($data['status'] == 'teacher'): ?>
    <script type='text/javascript' src='<?php print URL; ?>public/js/app/calendar/customselect/customselect.js'></script>
    <script type='text/javascript' src='<?php print URL; ?>public/js/app/calendar/setselect.js'></script>
    <script type='text/javascript' src='<?php print URL; ?>public/js/vendor/jQuery/jquery.mask.js'></script>
    <script src='<?php print URL; ?>public/js/app/calendar/teacher.js'></script>
    <script type='text/javascript' src='<?php print URL; ?>public/js/app/calendar/tcal/tcal.js'></script>
<?php else: ?>
    <script src='<?php print URL; ?>public/js/app/calendar/student.js'></script>
<?php endif; ?>
