    <link rel='stylesheet' href='<?php print URL; ?>public/css/calendar/popup.css'/>

<div class='popup' id='popup'>

    <form method='post' class='create-lesson'>
        <div class='tr-create-lesson'>
            <span class="bold cell-create-lesson cell-first-create-lesson">Тема: </span>
            <div class="cell-create-lesson cell-two-create-lesson">
                <input class='input-none input-create-lesson '  type='text' id='eventType' name='event_type'>
            </div>
        </div>

        <div class='tr-create-lesson'>
            <span class="cell-create-lesson cell-first-create-lesson bold">Время проведения:</span>
            <div class="cell-create-lesson cell-two-create-lesson">
                <div class='data'>
                    <input type='text' id='tcalInput' name='date' class='tcal' value='' />
                    <input class="input-none numder2" placeholder="&ndash;&ndash;" type='text'  name='day' id='day' />/
                    <input class="input-none numder2" placeholder="&ndash;&ndash;" type='text'  name ='month' id='month' />/
                    <input class="input-none numder4" placeholder="&ndash;&ndash;&ndash;&ndash;" type='text'  name='year' id='year' />
                </div >
                <div class='data'>
                    <input class="input-none numder2" type='text'  placeholder='&ndash;&ndash;'  name='hour-begin' id='hourBegin'/>:
                    <input class="input-none numder2" type='text'  placeholder='&ndash;&ndash;' name='minutes-begin' id='minutesBegin'/>-
                    <input class="input-none numder2" type='text' placeholder='&ndash;&ndash;' name='hour-end' id='hourEnd'/>:
                    <input class="input-none numder2" type='text' placeholder='&ndash;&ndash;' name='minutes-end' id='minutesEnd'/>
                </div>
            </div>
        </div>
<!---->
<!--        <div class="tr-create-lesson">-->
<!--                <span class="bold">Преподаватель: </span>-->
<!--                <select class="select-teacher" id="selectTeacher">-->
<!--                    <option value="0">Преподаватель 1</option>-->
<!--                    <option value="1">Преподаватель 2</option>-->
<!--                    <option value="2">Преподаватель 3</option>-->
<!--                    <option value="3">Преподаватель 4</option>-->
<!--                </select>-->
<!--        </div>-->
<!---->
<!--        <div class="tr-create-lesson">-->
<!--                <span class="bold">Пригласить: </span>-->
<!--                <div id="listGroups" class="list-groups">-->
<!---->
<!--                </div>-->
<!--        </div>-->
<!---->
<!--        <div class='tr-create-lesson'>-->
<!--                <button id='resetLesson' type='reset' class='reset '>Отмена</button>-->
<!--                <button id='createNewLesson' type='submit' class='submit'>Создать</button>-->
<!--        </div>-->
    </form>
</div>