<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Регистрация</title>
    <link rel="stylesheet" href="<?php print URL; ?>public/css/startPage/bootstrap.css"/>
    <link rel="stylesheet" href="<?php print URL; ?>public/css/startPage/start-page.css" />
    <link rel="stylesheet" href="<?php print URL; ?>public/css/startPage/mycss.css" />

</head>
<body>
<section class="form" id="regist">
    <h3>Регистрация</h3>
    <form class="form-horizontal panel panel-default block-regist">
        <fieldset>
            <div class="form-group">
                <label  class="col-md-2 control-label">Имя</label>
                <div class="col-md-10">
                    <input type="text" id="name" class="input" value="<?php echo $_SESSION['firstname']?>" data-bind="value:name,valueUpdate:'afterkeydown'" placeholder="">
                    <p class="error" id="name_error"></p>
                </div>
            </div>
            <div class="form-group">
                <label  class="col-md-2 control-label">Фамилия</label>
                <div class="col-md-10">
                    <input type="text" id="surname" class="input"  value="<?php echo $_SESSION['lastname']?>"data-bind="value:surname,valueUpdate:'afterkeydown'" placeholder="">
                    <p class="error" id="surname_error"></p>
                </div>
            </div>
            <div class="form-group">
                <label  class="col-md-2 control-label">E-mail</label>
                <div class="col-md-10">
                    <input type="text" id="surname" class="input"  value="<?php echo $_SESSION['email'];?>" placeholder="" disabled>
                    <p class="error" id="surname_error"></p>
                </div>
            </div>
            <div class="form-group">
                <label  class="col-lg-2 control-label">Телефон</label>
                <label  class="col-lg-1 control-label">+380 </label>
                <div class="col-lg-9">
                    <input type="text" id="phone" class="input"  data-bind="value:phone,valueUpdate:'afterkeydown'" placeholder="">
                    <p class="error" id="phone_error"></p>
                </div>
            </div>
            <div class="form-group">
                <label for="select" class="col-lg-2 control-label">Роль</label>
                <div class="col-lg-10">
<!--                    <select class="form-control" id="select" data-bind="options: rolesName,-->
<!--                       optionsText: rolesName,-->
<!--                       value: role-->
<!--                       "></select>-->
                    <div style="display: inline; margin-right: 10px">
                        <input type="radio" name="role" data-bind="checked: roleCkeck" value="false" />Cтудент</div>
                    <div style="display: inline">
                        <input type="radio" name="role" data-bind="checked: roleCkeck" value="true" />Вчитель</div>
<!--                    <div class="radio"><input type="radio" name="flavorGroup" value="0" data-bind="checked: role" checked="checked"/> Cтудент</div>-->
<!--                    <div class="radio"><input type="radio" name="flavorGroup" value="1" data-bind="checked: role" /> Вчитель</div>-->
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-10 col-lg-offset-2">
                    <div id="reset" class="button" hreff="<?php echo $_SESSION['logout_link'];?>">Отмена</div>
                    <div data-bind="click:sendInfo" class="button" >Создать</div>
                </div>
            </div>
        </fieldset>
    </form>
</section>
<section id="success">
    <div>
        <h2> Вы успешно зарегестрировались!</h2>
        <button class="btn btn-success" id="btn-success">Продолжить работу</button>
    </div>
</section>

<!--<script src="https://apis.google.com/js/client:platform.js"></script>-->
<script src="<?php print URL; ?>public/js/vendor/knockout-3.2.0.js"></script>
<script src="<?php print URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js"></script>
<script src="<?php print URL; ?>public/js/app/common.js"></script>
<!--<script src="-->
<!--public/js/app/signin/login1.js"></script>-->
<script src="<?php print URL; ?>public/js/app/signin/regist.js"></script>

</body>
</html>