<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>Заголовок страницы</title>
        <link rel="stylesheet" href="<?php print URL; ?>public/css/common/common.css" />
        <link rel="stylesheet" href="<?php print URL; ?>public/css/admin/admin.css"/>
        <link rel="stylesheet" href="<?php print URL; ?>public/css/user.css"/>
        <link rel="stylesheet" href="<?php print URL; ?>public/css/common/footer/footer.css">
    </head>
    <body>
        <footer class="footer">
            <div class="background"></div>
        </footer>
    </body>
</html>