<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>Заголовок страницы</title>
        <link rel="stylesheet" href="<?php print URL; ?>public/css/common/common.css" />
        <link rel="stylesheet" href="<?php print URL; ?>public/css/admin/admin.css"/>
        <link rel="stylesheet" href="<?php print URL; ?>public/css/user.css"/>
        <link rel="stylesheet" href="<?php print URL; ?>public/css/common/header/header.css">
    </head>
    <body>
        <header class="header">
            <div class="background"></div>
            <img class="logo" src="<?php print URL; ?>public/img/logo.png"/>
            <section class="login" id="login">
                <article class="user" id="activeUser">
                    <section class="info">
                        <h2 class="name" id="activeUserName">Саша Коваленко</h2>
                        <h3 class="role" id="activeUserRole">Администратор</h3>
                        <h3 class="logout" id="logout" onclick="logout();">Выйти из системы</h3>
                    </section>
                    <img class="avatar" id="activeUserPhoto" src="<?php print URL; ?>public/img/avatar.png" />
                </article>
            </section>
            <div class="clear-both"></div>
        </header>
        <script src="<?php print URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js"></script>
        <script src="<?php print URL; ?>public/js/app/common.js"></script>
        <script src="<?php print URL; ?>public/js/app/common/header/header.js"></script>
        <script>
            load();
        </script>
    </body>
</html>