<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/css/lesson/lesson.css">
<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/css/common/bootstrap.css">
<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/js/vendor/tcal/tcal.css">
<section class="main-content clearfix">
    <h2 class="col-lg-7">Домашнее Задание</h2>
    <h3 id="deadLine" class="col-lg-5">Дедлайн: <span data-bind="text:deadLine"></span></h3>
    <div class="col-lg-7"></div>
    <div id ="deadLineSettings" class="clearfix col-lg-5">
        <?php if ($data['status'] == 'teacher'): ?>
            <div class="error-deadline" data-bind="if:deadLineError">
                <div data-bind="text:deadLineErrorMessage"></div>
            </div>
            <input data-bind="value:day" placeholder="- -" id="day" type="tel"/>-
            <input data-bind="value:month" placeholder="- -" id="month" type="tel"/>-
            <input data-bind="value: year" placeholder="- - - -" id="year" type="tel"/>
            <input data-bind="value:deadLine" id="calen" class="tcal"/>
            <input data-bind="value: hour" id="hour" placeholder="14" min="0" max="23" type="number"/>:<input data-bind="value:minute" id="min" placeholder=" 00" min="0" max="59" type="number"/>
            <button data-bind="setDeadLine{ deadLine:deadLine}">Установить дедлайн</button>
         <?php endif ?>

    </div>
<div>
    <section class="col-md-7">
        <span data-bind="getName:{role:'<?php echo $data['status']?>', name:'<?php echo $data['name']?>', userId:'<?php echo $data['id']?>', userInfo:userInfo}"></span>

        <!-- ko ifnot: descriptionEdit-->
        <?php if ($data['status'] == 'teacher'): ?>
            <div class='description' data-bind="text:homeWorkDescription, click:descriptionEditStart">
                нажмите сюда для редактирования
            </div>
        <?php endif ?>
        <?php if ($data['status'] == 'student'): ?>
            <div class='description' data-bind="text:homeWorkDescription">нажмите сюда для редактирования</div>
        <?php endif ?>
        <!--/ko-->
        <!-- ko if: descriptionEdit-->
        <textarea class="descInput form-control " rows="5"
                  data-bind="value:homeWorkDescription, event: {blur: saveDesc}, hasFocus:true"></textarea>
        <!--/ko-->

    </section>
    <section class="content col-md-5 ">
        <div class="clearfix">
            <h4>Полезные ссылки:</h4>

            <div>
                <?php if ($data['status'] == 'teacher'): ?>
                    <input type="text" class="col-md-12" placeholder="Вставьте ссылку"
                           data-bind="value:linkToAdd,valueUpdate:'keypress', event: { keypress: saveLink }">

                <?php endif ?>
            </div>
            <div class="col-md-12 clearfix" data-bind="foreach:links">
                <div class="col-lg-10 wordBreak elipsis">
                    <a data-bind="text: name, attr: {href:name}" target="_blank">ссылка</a>
                </div>
                <?php if ($data['status'] == 'teacher'): ?>
                    <div class="col-lg-2 ">
                        <button class="deleteButton" data-bind="click: function(){$parent.deleteLink($data.name)}">
                            Удалить
                        </button>
                    </div>
                <?php endif ?>
            </div>
        </div>
        <h4>Файлы для скачивания:</h4>
        <?php if ($data['status'] == 'student'): ?>
        <div class='col-md-12 ' data-bind="foreach: files">
            <div class=" col-lg-10">
                <a download="" data-bind="text:newName, attr:{ href:url}">файл</a>
            </div>
            <?php endif ?>

            <?php if ($data['status'] == 'teacher'): ?>
            <div class='col-md-12 ' data-bind="foreach: files">
                <div class=" col-lg-10">
                    <a download="" data-bind="text:oldName, attr:{ href:url}">файл</a>
                </div>
                <div class="col-lg-2 ">
                    <button class="deleteButton" data-bind="click: function(){$parent.deleteFile($data.newName)}">
                        Удалить
                    </button>
                </div>
                <?php endif ?>
            </div>
            <?php if ($data['status'] == 'teacher'): ?>
                <button data-bind="uploadTask: { files: files, save: makeArray }">Загрузить файл</button>
                <div class="fileValid">Размер не больше 20 мБ</div>
            <?php endif ?>
    </section>
</section>
<section class="main-content clearfix ">
<?php if ($data['status'] == 'student'): ?>
    <!-- ko ifnot: deadLinePass-->
    <!-- ko ifnot: selfHomeWork-->
    <h4>Загрузка домашнего задания</h4>
    <button data-bind="uploadHomework{userInfo:userInfo, homeWork:homeWork, id:id} ">Загрузить
        файл</button>
    <!--/ko-->
    <!--/ko-->
    <!-- ko if: deadLinePass-->
    <!-- ko ifnot: selfHomeWork-->
    <h4>Загрузка домашнего задания</h4>
    <div> <span>Дедлайн прошел. Отправка домашнего задания невозможна</span></div>
    <!--/ko-->
    <!--/ko-->

    <!-- ko if: selfHomeWork-->
    <div data-bind="foreach: homeWork">
        <br><span>Вы уже загрузили домашнее задание</span> <a download="" data-bind="attr:{ href:link}">Скачать</a>
    </div>
    <!--/ko-->
<?php endif ?>
    <?php if ($data['status'] == 'teacher'): ?>
        <h4>Присланные решения</h4>

        <table class="table table-striped table-hover ">
            <thead>
            <tr>
                <th>Студент</th>
                <th>Домашнее задание</th>
                <th>Оценка</th>
                <th>Преподаватель</th>
            </tr>
            </thead>
            <tbody data-bind="foreach: homeWork">
            <!-- ko if: grade-->
            <tr>
                <td data-bind="text:name"></td>
                <td><a download="" data-bind="attr:{ href:link}">Скачать</a></td>
                <td><input type="text" class="col-lg-12" data-bind="value:grade,valueUpdate:'keypress'"></td>
                <td data-bind="text:teacher"> </td>
            </tr>
            <!--/ko-->
            <!-- ko ifnot: grade-->
            <tr  class="danger">
                <td data-bind="text:name"></td>
                <td><a download="" data-bind="attr:{ href:link}">Скачать</a></td>
                <td><input type="text" class="col-lg-12" data-bind="value:grade,valueUpdate:'keypress'"></td>
                <td data-bind="text:teacher"> </td>
            </tr>
            <!--/ko-->
            </tbody>
        </table>
    <?php endif ?>
</section>

ViewModel:
<pre data-bind="text: ko.toJSON($root, null, 2)"></pre>

<!--
<section class="main-content">
    <?php

$data = array(
    "id" => $data['id'],
    "username" => $data['name'],
    "email" => $data['email']
);
function dsq_hmacsha1($data, $key) {
    $blocksize=64;
    $hashfunc='sha1';
    if (strlen($key)>$blocksize)
        $key=pack('H*', $hashfunc($key));
    $key=str_pad($key,$blocksize,chr(0x00));
    $ipad=str_repeat(chr(0x36),$blocksize);
    $opad=str_repeat(chr(0x5c),$blocksize);
    $hmac = pack(
        'H*',$hashfunc(
            ($key^$opad).pack(
                'H*',$hashfunc(
                    ($key^$ipad) . $data
                )
            )
        )
    );
    return bin2hex($hmac);
}
$message = base64_encode(json_encode($data));
$timestamp = time();
$hmac = dsq_hmacsha1($message . ' ' . $timestamp, DISQUS_SECRET_KEY);
?>

<script type="text/javascript">
    var disqus_config = function() {
        this.page.remote_auth_s3 = "<?php echo "$message $hmac $timestamp"; ?>";
        this.page.api_key = "<?php echo DISQUS_PUBLIC_KEY; ?>";
    }
</script>


<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'schedule'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<!--<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>-->


</section>

<script src="<?php print URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js"></script>
<script type="text/javascript" src="<?php echo URL ?>public/js/app/common.js"></script>
<script src="<?php echo URL; ?>public/js/vendor/knockout-3.2.0.js"></script>
<script type="text/javascript" src="<?php echo URL ?>public/js/app/lesson/lesson.js"></script>
<script src="<?php echo URL; ?>public/js/vendor/tcal/tcal.js"></script>
<script>
</script>
