<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/css/lesson/lesson.css">
<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/css/lesson/comment.css">
<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/css/common/bootstrap.css">
<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/js/vendor/tcal/tcal.css">
<!-- ko with:viewModel -->
<div data-bind="attr:{class:loadScr}" id="loadScreen"><img src="<?php echo URL?>public/img/load.gif"></div>

<?php if ($data['status'] == 'teacher'): ?>
    <nav>
        <div class="tabButton taskButton activeTab"
             data-bind="changeTab:{tab:'descr',descriptionTab:descriptionTab, homeWork:homeWork}">Описание
        </div>
        <!--
                -->
        <div class="tabButton homeworkButton"
             data-bind="changeTab:{tab:'tasks',descriptionTab:descriptionTab, homeWork:homeWork}">Решения
        </div>
    </nav>
<?php endif ?>

<!-- ko if: descriptionTab-->
<section class="main-content clearfix">
    <h2 class="col-lg-7">Домашнее Задание</h2>

    <h3 id="deadLine" class="col-lg-5">Дедлайн: <span data-bind="text:deadLine"></span></h3>

    <div class="col-lg-7"></div>
    <div id="deadLineSettings" class="clearfix col-lg-5">
        <?php if ($data['status'] == 'teacher'): ?>
            <div class="error-deadline" data-bind="if:deadLineError">
                <div data-bind="text:deadLineErrorMessage"></div>
            </div>
            <input data-bind="value: day" placeholder="- -" id="day" type="tel"/>-
            <input data-bind="value: month" placeholder="- -" id="month" type="tel"/>-
            <input data-bind="value: year" placeholder="- - - -" id="year" type="tel"/>
            <input data-bind="value: deadLine" id="calen" class="tcal"/>
            <input data-bind="value: hour" id="hour" placeholder="14" min="0" max="23" type="number"/>:<input
                data-bind="value:minute" id="min" placeholder=" 00" min="0" max="59" type="number"/>
            <button data-bind="setDeadLine{ deadLine:deadLine}">Установить дедлайн</button>
        <?php endif ?>

    </div>

    <section class="col-md-7 clearfix">
        <span
            data-bind="getName:{role:'<?php echo $data['status'] ?>', name:'<?php echo $data['name'] ?>', userId:'<?php echo $data['id'] ?>', userInfo:userInfo}"></span>

        <!-- ko ifnot: descriptionEdit-->
        <?php if ($data['status'] == 'teacher'): ?>
            <div class='description' data-bind="text:homeWorkDescription, click:descriptionEditStart">
                нажмите сюда для редактирования
            </div>
        <?php endif ?>
        <?php if ($data['status'] == 'student'): ?>
            <div class='description' data-bind="text:homeWorkDescription">нажмите сюда для редактирования</div>
        <?php endif ?>
        <!--/ko-->
        <!-- ko if: descriptionEdit-->
        <textarea class="descInput form-control " rows="5"
                  data-bind="value:homeWorkDescription, event: {blur: saveDesc}, hasFocus:true"></textarea>
        <!--/ko-->

    </section>
    <section class="content col-md-5 clearfix ">
        <div class="clearfix">
            <h4>Полезные ссылки:</h4>

            <div>
                <?php if ($data['status'] == 'teacher'): ?>
                    <input type="text" class="col-md-12" placeholder="Вставьте ссылку"
                           data-bind="value:linkToAdd,valueUpdate:'keypress', event: { keypress: saveLink }">

                <?php endif ?>
            </div>
            <div class="col-md-12 clearfix" data-bind="foreach:links">
                <div class="col-lg-12 wordBreak elipsis">
                    <a data-bind="text: nameLink, attr: {href:name}" target="_blank">ссылка</a>
                    <?php if ($data['status'] == 'teacher'): ?>
                        <button class="deleteButton fixes"
                                data-bind="click: function(){$parent.deleteLink($data.name)}">
                            Удалить
                        </button>
                    <?php endif ?>
                </div>
            </div>
        </div>
        <h4>Файлы для скачивания:</h4>
        <?php if ($data['status'] == 'student'): ?>
        <div class='col-md-12 ' data-bind="foreach: files">
            <div class=" col-lg-10">
                <a download="" data-bind="text:newName, attr:{ href:url}">файл</a>
            </div>
            <?php endif ?>

            <?php if ($data['status'] == 'teacher'): ?>
            <div class='col-md-12 ' data-bind="foreach: files">
                <div class=" col-lg-12">
                    <a class="file-link" download="" data-bind="text:oldName, attr:{ href:url}">файл</a>
                    <button class="deleteButton fixes" data-bind="click: function(){$parent.deleteFile($data.newName)}">
                        Удалить
                    </button>
                </div>
                <?php endif ?>
            </div>
            <?php if ($data['status'] == 'teacher'): ?>
                <button data-bind="uploadTask: { files: files, save: makeArray }">Загрузить файл</button>
                <div class="fileValid">Размер не больше 20 мБ</div>
            <?php endif ?>
    </section>
</section>
<!--/ko-->


<section class='main-content'>

        <?php if ($data['status'] == 'student'): ?>
    <div class="cont col-lg-7 ">
           <div data-bind="ifnot: selfHomeWork">

               <div data-bind="if:deadLinePass">
                   <span class="sad">Дедлайн прошел. Отправка решения не возможна.</span>
               </div>
               <div data-bind="ifnot: deadLinePass">
                   <span>Вы еще не загрузили свое решение.</span>
                   <button data-bind="uploadHomework{userInfo:userInfo, homeWork:homeWork, id:id} ">Загрузить решение</button>
               </div>
           </div>
            <div data-bind="if: selfHomeWork">
                <div class="stud ">
                <div data-bind="foreach:homeWork">
                        <span><strong>Ваше решение загружено.</strong></span><br/>
                        <span><strong>Оценка: </strong><span data-bind="text:grade"></span></span><br/>
                    <!-- ko if: $parent.haveGrade-->
                        <span><strong>Проверил: </strong><span data-bind="text: teacher"></span> в <span data-bind="text: time"></span></span><br/>
                    <!--/ko-->
                        <a download="" data-bind="attr:{ href:link}">Загрузить присланное решение.</a><br>
                    <!-- ko ifnot: $parent.haveGrade-->
                        <!-- ko ifnot: $parent.deadLinePass-->
                        <span><strong>Также Вы можете:</strong></span>
                    <button class="load-btn" data-bind="uploadHomework{userInfo:$root.viewModel.userInfo, homeWork:$root.viewModel.homeWork, id:$root.viewModel.id} ">Загрузить новое решение</button>
                        <!--/ko-->
                    <!--/ko-->
                </div>

                </div>
            </div>
    </div>
            <div class="col-lg-5"></div>
        <?php endif ?>
</section>

<!-- ko ifnot: descriptionTab-->
<section class="main-content clearfix ">

    <?php if ($data['status'] == 'teacher'): ?>
        <div class="homeWorkList " data-bind="foreach: homeWork">

        <div class="col-lg-3 task">
            <img height="50" width="50" class="ownerPic" data-bind="attr:{src:userPicture}">
            <span data-bind="text:name"></span>'




            <button><img width="20"height="20" src="<?php echo URL ?>public/img/dearchive.png"></button>


        </div>



<!--
               <div class="list-group-item clearfix">
                <div class="col-lg-5">
                    <span data-bind="text:name"></span>
                    <br><a download="" data-bind="attr:{ href:link}">Скачать</a>
                </div>
                <div class="col-lg-5">
                    <span>Оценка :</span>
                    <span data-bind="text:grade"></span>
                    <br><span>Преподаватель:</span>
                    <span data-bind="text:teacher"></span>
                </div>
                <div class="col-lg-2">
                    <button data-bind="click: $parent.showInput">Оценить</button>
                </div>
                <!-- ko if: $root.viewModel.rateStudent-->
                <!-- ko if: $data.rateStudent-->
            <!--
                <input type="text" class="col-lg-12"
                       data-bind="value:grade, valueUpdate:'keypress', event: { keypress: $parent.setRate },hasFocus:true" placeholder="Введите оценку и нажмите enter">
                <!--/ko-->
         <!--   </div> -->


        </div>

    <?php endif ?>
</section>

<!--/ko-->
<!--/ko-->
<section class="main-content">
    <!-- ko with:commentModel -->
    <script id="treeElement" type="text/html">
        <!-- ko if:$data.id -->
        <div class="comment-container">
            <div class="comment-container-img">
                <img class="comment-img" data-bind="attr:{src:$data.photo}"/>
            </div>
            <div class="comment-body">
                <header>
                    <span class="comment-name" data-bind="text: name"></span><span class="comment-date" data-bind="text: date"></span>
                </header>
                <div class="comment-text" data-bind="text:text">
                </div>
                <div class="comment-footer">
                    <!-- ko if:$data.user_id()==$root.commentModel.currentUser().id -->
                       <span class="comment-remove" data-bind="click:function($data){
                                                $parent.remove($data);
                                        }">Удалить</span>
                    <!-- /ko -->
                    <span class="comment-reply" data-bind="click:addNewItem">Ответить</span>
                    <!-- ko if:$data.reply()-->
                    <div  class="comment-wrap" data-bind="template: { name: 'form', data:$data }"></div>
                    <!-- /ko -->
                </div>
            </div>
        </div>
        <!-- /ko -->
        <div class="comment-wrap" data-bind="template: { name: 'treeElement', foreach: children }">
        </div>
    </script>
    <script id="form" type="text/html">
        <div class="comment-form">
            <div class="comment-textarea-container">
                <textarea data-bind="value:textForComment,handleTextareaAutogrow:$data.reply()"></textarea>
            </div>
            <div class="comment-answer-container">
                <div class="custom-button comment-answer-button" data-bind="click:sendNewComment">Опубликовать</div>
            </div>
    </script>
    <!--<div class="container-img">-->
    <!--    <img class="img" src="http://a.disquscdn.com/uploads/users/14338/9498/avatar92.jpg?1423742151"/>-->
    <!--</div>-->
    <div  class="comment-wrap" data-bind="template: { name: 'form', data:$root.commentModel }"></div>
    <div  class="comment-wrap" data-bind="template: { name: 'treeElement', foreach: $data.treeRoot }"></div>

    <!--/ko-->
</section>

<script type="text/javascript" src="<?php print URL; ?>public/js/vendor/jQuery/jquery-2.1.1.js"></script>
<script type="text/javascript" src="<?php echo URL ?>public/js/app/common.js"></script>
<script type="text/javascript" src="<?php echo URL; ?>public/js/vendor/knockout-3.2.0.js"></script>
<script type="text/javascript" src="<?php echo URL ?>public/js/app/lesson/comment.js"></script>
<script type="text/javascript" src="<?php echo URL ?>public/js/app/lesson/lesson.js"></script>
<script type="text/javascript" src="<?php echo URL; ?>public/js/vendor/tcal/tcal.js"></script>
<script>
</script>
